### ISSUE TITLE
Divide by 16 in conv reference?

### ISSUE THREAD

**Issue by dillonhuff** [David-Durst/embeddedHaskellAetherling#24]
@David-Durst the output of each conv is divided by 16 in the conv test:

https://github.com/David-Durst/embeddedHaskellAetherling/blob/87b7cf10c6b07950a9fe185bd236fa746bb7789d/other/conv.cpp#L45

Should there be an extra stage in the conv app that does this pointwise divide or is that a leftover that can be ignored?

**Comment by David-Durst** [comment]
Is your question whether there should be a divide or whether it should be its own stage?

The divide needs to be there. The conv averages values together. The average requires dividing by the sum of the coefficients, 16. Since 16 is a power of 2, the divide can be implemented with a shift.

I don't know whether in Halide it should be its own stage or part of a prior stage.

Did I answer your question?

**Comment by dillonhuff** [comment]
Yes. I'll commit a testbench and modified app soon.
