### ISSUE TITLE
Unexpected output pattern for conv2d_b2b reference, am I missing something?

### ISSUE THREAD

**Issue by dillonhuff** [David-Durst/embeddedHaskellAetherling#50]
@David-Durst I'm working on big_conv2d_b2b_real. Since the input is 1920 columns by 1080 rows I was expecting the output to be of size: (1920 - 3) * (1080 - 3) = 2064609, but when I scan over the json file filtering all values that are not "253" I get: 2064605 values, four less than what I would expect.

Also I looked at the output and the 4 unexpected values are in an odd spot: 250 columns into the first valid row of output (at offsets 6012, ..., 6015 in the json output file).

Am I misunderstanding something about the output format? The first line of output seems to match up to that point.

**Comment by David-Durst** [comment]
Those contained 253 normally, therefore the outputs are 253 since the testing code sees 253 and thinks the input id undefined. I had to choose 1 invalid value < 255 to work for the 8 bit ints. I'm gonna leave it the same for 32 bit ints. The tradeoff is that this issue occurs

For all the outputs at indices 6012 to 6015, one of the inputs is 253 as:
1. The value 253 occurs at index 252 since the input starts at 1.
2. The support (region of inputs that affects an output) is a 4x4 box since its 2x2 fed from a 3x3.
3. 6012 - (1920*3) = 252, so that output has 253 as the top, right most pixel
4. This continues for 4 consecutive outputs (6013, 6014, 6015) as the support for those regions also covers the 253

Make sense?

**Comment by dillonhuff** [comment]
@David-Durst I see. In that case I will just ignore any pixel with value 253 in regions where I am expecting valid output.
